[plugin]
id = "ai-googleapis-vertex-compiler-plugin"
class = "io.ballerina.lib.ai.googleapis.vertex.compiler.AiVertexAICompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.googleapis.vertex-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-@ballerinaToOpenApiVersion.version@.jar"
